sudo: required

language: java

jdk:
  - oraclejdk8

env:
  - >-
   KEY_PATH=$PWD/id_rsa_test

services:
  - docker

before_install:
  - ssh-keygen -t ecdsa -f ${KEY_PATH} -N ''
  - docker-compose up -d
  - docker-compose ps

script:
  - ./gradlew checkstyle
  - ./gradlew --info check
