sudo: required

language: java

jdk:
  - oraclejdk8

env:
  - >-
   BASE_YAML=$PWD/src/test/resources/yaml/base.yml
   KEY_PATH=$PWD/id_rsa_test

services:
  - docker

before_install:
  - ssh-keygen -f ${KEY_PATH} -N ''
  - docker build -t eg_sshd .
  - >-
    docker run -d
    -p 10022:22
    -v ${PWD}/src/test/resources/input/:/mount
    -v ${PWD}/id_rsa_test.pub:/root/.ssh/authorized_keys
    --name test_sshd
    eg_sshd
  - docker ps -a

script:
  - ./gradlew --info check
