sudo: required

language: java

jdk:
  - oraclejdk8

env:
  - YAML_TEST01=$PWD/src/test/resources/yaml/test01.yml

services:
  - docker

before_install:
  - docker build -t eg_sshd .
  - docker run -d -p 10022:22 -v $PWD/src/test/resources/input:/mount --name test_sshd eg_sshd
  - docker ps -a

script:
  - ./gradlew --info check
