version: '3'
services:
  host1:
    container_name: embulk-input-remote_host1
    image: "kamatama41/ubuntu-sshd"
    ports:
     - "10022:22"
    volumes:
     - ./src/test/resources/input/host1/:/mount
  host2:
    container_name: embulk-input-remote_host2
    image: "kamatama41/ubuntu-sshd"
    ports:
     - "10023:22"
    volumes:
     - ./src/test/resources/input/host2/:/mount
